### ISSUE TITLE
parameter names all over the place

### ISSUE THREAD

**Issue by j-m-hoffmann** [darklang/tablecloth#23]
in List, list parameter is named l, ls or xs.
think we should stick to one.
i often renamed ls to l and chose a in the Array module,
but xs would make it more uniform.
Suggestions?

**Comment by j-m-hoffmann** [comment]
same with destructuring
hd :: tl
x :: xs

**Comment by j-m-hoffmann** [comment]
l_ :: ls_

**Comment by pbiggar** [comment]
Agreed. Let's:

- list params are l
- pattern matches use either `l` if focusing on the fact that it's a list, or `x :: rest` if focusing on the values.

**Comment by wpcarro** [comment]
Unsure if this issue is open for discussion, and I also apologize for chiming in because I think my comments are mostly squabble.

One benefit of preferring `xs` and `x :: xs` is that `xs` can be used for `List`, `Array`, `Set`, and many other "container" data types whereas `l` feels a bit strongly coupled to `List`. Should we then use `a` for `Array` and `s` for `Set`?

Feel free to close this because it's not something I feel terribly strongly about. Just wanted to voice my opinion.

**Comment by pbiggar** [comment]
I have softened on this. `x :: xs` sounds good.

**Comment by Dean177** [comment]
The substantial #136 and #137 PR's should have gone a long way to making these consistent.
