### ISSUE TITLE
Fold signature - `t` first / last

### ISSUE THREAD

**Issue by Dean177** [darklang/tablecloth#35]
Currently Tablecloth sticks to Elm's API by naively using `flip` in the implementation of fold for Lists / Arrays.

@j-m-hoffman showed this had some pretty disastrous consequences for performance in a benchmark so it looks like we have two options:
- Revert to the `'b -> 'a -> 'b` type signature
- Re-implement foldLeft / foldRight from scratch to have the Elm signatures.

It's actually kinda a big deal, as making it ergonomic to use with the rest of the library means we have to ensure all of the other modules have API's that permit "non-flipped" usage 

e.g. Having `foldLeft` take `f : 'a -> 'b -> 'b` means that we should also make sure that the signature for `Set.add` is `'a -> 'a t -> 'a t`.

This means making a commitment to either:
1. t-last like Elm
2. t-first like Belt
3. t-middle aka all of the optional arguments come first, then the `t` then any non-labelled arguments then the labelled arguments aka the approach of Base / Core.

I would be in favour of either 1 or 3, I think being able to consistently use `|>` is important:
- I am not a huge fan of the mental overhead of having to switch between `->` and `|>` when using Belt
- It actually gets a lot of recognition outside of the OCaml ecosystem thanks to the likes of Elixir and some JS proposals.
- I think labels provide a great user experience compared the the API on offer in Elm / Belt, and usage of labels is one of the stated goal's of Tablecloth.

_Originally posted by @Dean177 in https://github.com/darklang/tablecloth/pull/27_

**Comment by wpcarro** [comment]
I agree that standardizing on the position of these arguments benefits the developer. In this respect I think Elixir's core libraries are a beautiful model. See Elixir's [Enum module](https://hexdocs.pm/elixir/Enum.html) as an example. I believe Elixir prioritizes *t-first* because these cooperate with its `|>` operator (actually a macro), which pipes arguments into the first position.

I think that designing the APIs to cooperate with `|>` is a good idea, but I'm new to this ecosystem, so my opinions aren't strong.

Another idea is to change the positional arguments to kwargs named `t` or something else. I'm not wild about this idea, but I've heard convincing arguments in favor of enforcing kwargs for all function arguments.
